common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/', views.mypage, name='mypage'),
    path('group/create/', views.group_create, name='group_create'),
    path('group/list/', views.group_list, name='group_list'),
    path('group/mylist/', views.group_mylist, name='group_mylist'),
    #path('group/invite/<int:group_id>/', views.group_invite, name='group_invite'),
    path('group/invite/', views.group_invite, name='group_invite'),
    # path('group/search/', search_group, name='search_group'),
    # path('group/filter/', filter_groups, name='filter_groups'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base
    path('list/', base_views.list, name='list'),
    path('mylist/', base_views.mylist, name='mylist'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('', base_views.index, name='index'),

    # model
    path('question/modelcreate/', question_views.question_modelcreate, name='question_modelcreate'),

    # question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('question/result/', question_views.question_result, name='question_result'),

    # answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import User

class CustomGroup(models.Model):
    name = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    leader = models.ForeignKey(User, on_delete=models.CASCADE)
    introduction = models.TextField(null=True, blank=True)
    create_date = models.DateTimeField()
    members = models.ManyToManyField(User, related_name='custom_groups')

    def __str__(self):
        return self.name

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
from pybo.utils import rename_imagefile_to_uuid

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    location = models.CharField(max_length=200, null=True, blank=True)
    audio = models.FileField(upload_to='audio/', null=True, blank=True)
    image = models.FileField(upload_to='image/', null=True, blank=True)
    npz = models.FileField(upload_to='npz/', null=True, blank=True)
    output = models.FileField(upload_to='output/', null=True, blank=True)
    group = models.CharField(max_length=225, null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import CustomGroup as Group


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]


class GroupCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = Group
        fields = ['name', 'password', 'introduction']
        labels = {
            'name' : '그룹이름',
            'password' : '그룹비밀번호',
            'introduction' : '그룹소개',
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from common.forms import UserForm, GroupCreationForm
from django.contrib.auth.models import User
from .models import CustomGroup as Group
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages
from pybo.models import Question
from django.core.paginator import Paginator


@login_required
def group_create(request):
    if request.method == 'POST':
        form = GroupCreationForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.leader = request.user
            group.create_date = timezone.now()
            group.save()
            group.members.add(request.user)
            group.save()
            return redirect('common:mypage')  # 마이페이지로 이동
    else:
        form = GroupCreationForm()
    return render(request, 'common/group_create.html', {'form': form})



@login_required
def group_invite(request):
    if request.method == 'POST':
        input_password = request.POST['input_password']
        group_name = request.POST['group_name']
        try:
            group = Group.objects.get(name=group_name)
        except Group.DoesNotExist:
            messages.error(request, 'Invalid group name')  # Display error message
            return render(request, 'common/group_invite.html', {'error_messages': messages.get_messages(request)})
        
        if group.password == input_password:
            group.members.add(request.user)
            return redirect('common:group_list')  # Redirect to the group list page
        else:
            messages.error(request, 'Invalid password')  # Display error message
            return render(request, 'common/group_invite.html', {'error_messages': messages.get_messages(request)})
    else:
        return render(request, 'common/group_invite.html')


def group_list(request):
    groups = Group.objects.all()
    return render(request, 'common/group_list.html', {'groups': groups})

def group_mylist(request):
    groups = request.user.custom_groups.all()
    return render(request, 'common/group_mylist.html', {'groups': groups})

    
def mypage(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목
            Q(content__icontains=kw) |  # 내용
            Q(location__icontains=kw) |  # 장소
            Q(answer__content__icontains=kw) |  # 답변 내용
            Q(author__username__icontains=kw) |  # 질문 글쓴이
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    groups = request.user.custom_groups.all() # 내가 속한 그룹
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'groups': groups}
    return render(request, 'common/mypage.html', context)



"""def search_group(request):
    groups = CustomGroup.objects.all()
    return render(request, 'search_group.html', {'groups': groups})
    
def filter_groups(request):
    if request.method == 'GET' and request.is_ajax():
        query = request.GET.get('query')
        groups = CustomGroup.objects.filter(name__icontains=query)
        return render(request, 'group_search_list.html', {'groups': groups})"""
    
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/group_create.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form method="POST" action="{% url 'common:group_create' %}" class="post-form my-3">
      {% csrf_token %}
      <div class="mb-3">
        <label for="name" class="form-label">Group 이름</label>
        <input type="text" class="form-control" name="name" id="name"
                      value="{{ form.subject.value|default_if_none:'' }}">
      </div>
      <div>
        <label for="name" class="form-label">Group 소개</label>
        <textarea class="form-control" name="introduction"
        id="introduction" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>          
      </div>
      <div>
        <label for="password" class="form-label">Group 가입용 비밀번호</label>
        <input type="text" class="form-control" name="password" id="password"
            value="{{ form.location.value|default_if_none:'' }}">
      </div>
        <button class="btn btn-success btn-block btn-lg align-center" type="submit" style="text-align:center; margin-top:20px">Create Group</button>
    </form>
    <div class="col-12">
        <a href="{% url 'common:mypage' %}" class="btn btn-warning" style="float:right; margin-top:20px">마이페이지로 돌아가기</a>
    </div>
</div>
{% endblock %}
<!-- 
<div class="container">
    <form method="post" >
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="location" class="form-label">위치</label>
            <input type="text" class="form-control" name="location" id="location"
                   value="{{ form.location.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
    </form>
</div> -->

templates/common/group_delete.html
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:group_delete' %}">
        <div class="mb-3">
            <label for="username">그룹 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">그룹 생성하기</button>
    </form>
</div>
{% endblock %}

templates/common/group_invite.html
{% extends "base.html" %}
{% block content %}
{% if error_message %}
<p>{{ error_message }}</p>
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class="box-padding-big white-bg" style="border-radius:5px">
        <div class="container align-center">
			<h1><strong>Room Join</strong></h1>	
            <div>
                {% for message in error_messages %}
                    <p style="color:red">{{message}}!</p>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-md-6 info-big">
                    <div style="width: 100%; padding-bottom:10%; padding-top:10%; border:5px solid #064635; border-radius:10px;">
                        <h4>
                            <label for="group_id">Room Name</label><br>
                        </h4>
                        <input type="text" name="group_name" id="group_name" placeholder="그룹명을 입력하세요"><br>
                    </div>
                </div>
                <div class="col-md-6 info-big">
                    <div style="width: 100%; padding-bottom:10%; padding-top:10%; border:5px solid #064635; border-radius:10px;"> 
                        <h4>
                            <label for="username">Join Code</label><br>
                        </h4>
                        <input type="text" name="input_password" id="input_password" placeholder="비밀번호 입력하세요"><br>
                    </div>
                </div>
                <input type="submit" class="btn btn-success btn-block btn-lg" style="margin-top: 5%; margin-bottom:2%" value="방 참여하기">
                <a href="{% url 'common:mypage' %}">마이페이지로 돌아가기</a>
            </div>	
			
		</div>
	</div>
</form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#search-input').on('keyup', function() {
                var query = $(this).val();
                $.ajax({
                    url: '/filter_groups/',
                    type: 'GET',
                    data: {'query': query},
                    success: function(data) {
                        $('#group-list').html(data);
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/common/group_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Group List</h1>
    <ul>
        <li>| 그룹아이디 | 그룹이름 | 그룹리더 | 그룹비번 | 그룹소개 | 그룹생성시간 |</li>
        {% for group in groups %}
            <li>{{ group.id }} : {{ group.name }} : {{ group.leader }} : {{ group.password }} : {{ group.introduction }} : {{ group.create_date }}</li>
            <ul>
                {% for member in group.members.all %}
                    <li>{{ member.username }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
    <a href="{% url 'common:mypage' %}">마이페이지로 돌아가기</a>
{% endblock %}

templates/common/group_mylist.html
{% extends "base.html" %}
{% block content %}
    <h1>Group List</h1>
    <ul>
        <li>| 그룹아이디 | 그룹이름 | 그룹리더 | 그룹비번 | 그룹소개 | 그룹생성시간 |</li>
        {% for group in groups %}
            {% if group.leader == user %}
                내가 팀장인 방
            {% endif %}
            <li>{{ group.id }} : {{ group.name }} : {{ group.leader }} : {{ group.password }} : {{ group.introduction }} : {{ group.create_date }}</li>
            <ul>
                {% for member in group.members.all %}
                    <li>{{ member.username }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
    <a href="{% url 'common:mypage' %}">마이페이지로 돌아가기</a>
{% endblock %}

templates/common/group_search_list.html
{% for group in groups %}
    <li>{{ group.name }}</li>
{% empty %}
    <li>검색 결과가 없습니다.</li>
{% endfor %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3" >
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}"
                   style="border-radius: 15px border: solid 2px #064635">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}"
                   style="border-radius: 15px border: solid 2px #064635">
        </div>
        <div style="text-align: center">
            <button type="submit" class="btn btn-warning">Sign in</button>
        </div>
    </form>
</div>
{% endblock %}

templates/common/mypage.html
{% extends "base.html" %}
{% load pybo_filter %}
{% block content %}
<!-- <div>

    <ul>
        <li>
            <a href="{% url 'common:group_list' %}">그룹 리스트보기</a>
        </li>
        <li>
            <a href="{% url 'common:group_create' %}">그룹 생성하기</a>
        </li>
        <li>
            <a href="{% url 'common:group_invite' %}">그룹 참여하기</a>
        </li>
        <li>
            <a href="{% url 'common:group_mylist' %}">내가 속한 그룹</a>
        </li>
        <li>
            <a href="{% url 'pybo:mylist' %}">내가 생성한 모델 보기</a>
        </li>
    </ul>

</div> -->

<div class="box-padding-big white-bg">
	<div class="container align-center">
		<div class="row">
            <!-- 내 모델 보기 -->
<div class="col-md-4 info-big my-3">
    <h3><strong>My own models</strong></h3>
    <table class="table" >
        <thead>
        <tr class="text-center">
            <th style="background-color:#064635; color:white">번호</th>
            <th style="width:50%; background-color:#064635; color:white">제목</th>
            <th style="background-color:#064635; color:white">작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
            {% if request.user == question.author %}
            <tr class="text-center">
                <td>
                    <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td class="text-start">
                    <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                    {% if question.answer_set.count > 0 %}
                        <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endif %}
        {% endfor %}

        {% else %}
        <tr>
            <td colspan="3">생성한 모델이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
            <!-- 내 방 리스트 -->
            <div class="col-md-4 info-big my-3 align-center">
                <h3><strong>My rooms</strong></h3>
                <ul>
                    {% if groups%}
                    {% for group in groups %}
                        {% if group.leader == user %}
                            <img src="/static/images/master2.png" style="width:13%; height:13%">
                        {% else %}
                            <img src="/static/images/master2.png " style="width:13%; height:13%; opacity: 0;">
                        {% endif %}

                        <div class="btn btn-success btn-lg" style="margin-top:10px; height:60px; width:60%">{{ group.name }}</div>
                    {% endfor %}
                    {% else %}
                    속한 그룹이 없어용
                    {% endif %}
                </ul>

                <a href="{% url 'common:group_create' %}" class="btn btn-warning btn-lg" style="border:none; margin:5%">새방 만들기</a>
                <a href="{% url 'common:group_invite' %}" class="btn btn-warning btn-lg" style="border:none; margin:5%">방 들어가기</a>
                    
                    
            </div>
            <!-- 구매한 모델 -->
            <div class="col-md-4 info-big my-3">
				<h3><strong>Purchased models</strong></h3>	
            <table class="table" >
                <thead>
                    <tr class="text-center">
                        <th style="background-color:#064635; color:white">번호</th>
                        <th style="width:50%; background-color:#064635; color:white">모델명</th>
                        <th style="background-color:#064635; color:white">다운로드일시</th>
                    </tr>
                </thead>
                <tbody>
                   <tr class="text-center"> 
                       <td>
                       </td>
                       <td>
                           <div class="btn btn-outline-warning btn-sm">model name</div><br>
                       </td>
                       <td> 
                       </td>
                </tbody>
                </table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div style="text-align: center">
            <button type="submit" class="btn btn-warning">Sign up</button>
        </div>
    </form>
</div>
{% endblock %}